---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/default

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: fedora-27
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: chef-14
    run_list:
      - recipe[timezone_test]
  - name: chef-13
    run_list:
      - recipe[timezone_test]
    includes:
      - ubuntu-16.04
    provisioner:
      require_chef_omnibus: 13
