---
driver:
  name: vagrant
  ssh:
    insert_key: false


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/precise64
  - name: ubuntu/trusty64
  - name: ubuntu/xenial64
    driver:
      ssh:
        insert_key: true
  - name: debian/wheezy64
  - name: debian/jessie64
  - name: centos/6
  - name: centos/7
  - name: bento/fedora-22
  - name: bento/fedora-23
  - name: bento/fedora-24


suites:
  - name: default
    run_list:
      - recipe[timezone_test]