---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.8

suites:
  - name: default
    run_list:
      - recipe[timezone_test]