---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  inspec_tests:
    - path: test/integration/default

platforms:
  - name: bento/ubuntu-14.04
  - name: bento/ubuntu-16.04
  - name: bento/debian-8
  - name: bento/debian-9
  - name: bento/centos-6
  - name: bento/centos-7
  - name: bento/fedora-26
  - name: bento/fedora-27

suites:
  - name: chef-14
    run_list:
      - recipe[timezone_test]
  - name: chef-13
    run_list:
      - recipe[timezone_test]
    includes:
      - bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 13