---
driver:
  name: digitalocean

driver_config:
  private_networking: false
  region: nyc3

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12-04-x64
  - name: ubuntu-14-04-x64
  - name: debian-7-0-x64
  - name: centos-6-5-x64
  - name: centos-7-0-x64
  - name: fedora-21-x64
  - name: fedora-22-x64

suites:
  - name: default
    run_list:
      - recipe[timezone_test]